### ISSUE TITLE
Question regarding the input to the network described in the paper

### ISSUE THREAD

**Issue by iacopo97** [timbroed/MUSES#4]
good morning, I would like to know which input size has been used to your networks?

**Comment by timbroed** [comment]
we use a image_size of 1024 x 1024

**Comment by iacopo97** [comment]
If i want to submit a model for semantic segmentation task, do I need to provide the weights of the models? Which will be the results if i set the flags to 
All
Day
Night
Clear
Fog
Rain
Snow
You are going to provide me mIoU for each case or also the subcases: i.e. mIoU for fog_night and mIoU for fog_day?

**Comment by timbroed** [comment]
You do not need to upload the weights (that is just an additional option). Instead, you should upload your predictions for each image in the trainIDs format. For semantic segmentation, we have these upload requirements:

-  Zip structure:
     -  yourSubmission.zip
         - labelTrainIds/     
-  Result files with filename "{sequence}_frame_{frame:0>6}*.png" (i.e. REC0124_frame_208369.png) for all images. The files can be in arbitrary locations inside "labelTrainIds/".
- Exactly one result file per test image.
- Image dimensions of result files must be equal to input RGB image dimensions, i.e., 1920 x 1080.
- Labels must be encoded in trainIDs format, e.g., road should correspond to ID 0. 

For each flag that you set, we will run a separate evaluation with its on result on this subset of the test set We will provide you with an mIoU (and also per class results) for each of the cases selected. But we do not do not test for combined subcases cases like fog_night.

**Comment by iacopo97** [comment]
Thank you very much for your answer!
